# array_split , column_stack , concatenate , diagonal , dsplit , dstack , hsplit , hstack , ndarray.item , newaxis , ravel , repeat , reshape , resize , squeeze , swapaxes , take , transpose , vsplit , vstack

In [1]:
import numpy as np

In [2]:
## Split an array into multiple sub-arrays.
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [3]:
## Stack 1-D arrays as columns into a 2-D array.
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [4]:
## concatenate - Join a sequence of arrays along an existing axis.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [6]:
np.concatenate((a, b.T), axis=None)

array([1, 2, 3, 4, 5, 6])

In [7]:
## Split array into multiple sub-arrays along the 3rd axis (depth).
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [8]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [9]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

In [10]:
## Stack arrays in sequence depth wise (along third axis).
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [11]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [12]:
## Split an array into multiple sub-arrays horizontally (column-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [13]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [14]:
## Stack arrays in sequence horizontally (column wise).
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [15]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
## Revel - Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [17]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

In [18]:
## Repeat elements of an array.
np.repeat(3, 4)

array([3, 3, 3, 3])

In [19]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [20]:
np.repeat(x,3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [21]:
np.repeat(x,[1,2],axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

In [22]:
## Gives a new shape to an array without changing its data.
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.reshape(a, (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [25]:
## Resize - Return a new array with the specified shape.
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [26]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [27]:
np.resize(a,(2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [28]:
## swapaxes - Interchange two axes of an array.
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [29]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [31]:
## Reverse or permute the axes of an array; returns the modified array.
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [32]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [33]:
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

In [34]:
x = np.ones((2, 3, 4, 5))
np.transpose(x).shape

(5, 4, 3, 2)

In [35]:
## Vsplit - Split an array into multiple sub-arrays vertically (row-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [36]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [37]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [38]:
## Vstack - Stack arrays in sequence vertically (row wise).
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
np.all([[True,False],[True,True]])

False