# The Basic

In [1]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [3]:
#Get Dimension
a.ndim

1

In [4]:
b.ndim

2

In [5]:
# Get Shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('float64')

In [9]:
# Get size
a.itemsize

4

In [10]:
b.itemsize

8

In [11]:
# Get Total size
a.nbytes

12

In [12]:
b.nbytes

48

# Accesing/Changing Specific elements, rows, columns, etc.

In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get specific elements [r,c]
a[1,5]

13

In [15]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 5]

array([ 6, 13])

In [17]:
# Geting a little more fancy [startindex:endindix:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
a[1,5]=20

a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# *3-D Example

In [19]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific Element (work outside in)
b[0,1,1]

4

In [21]:
# replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Array

In [22]:
## All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Randpm decimal number
np.random.rand(4,2)


array([[0.32209081, 0.70630159],
       [0.15626084, 0.13731445],
       [0.85287216, 0.13127802],
       [0.5311049 , 0.86918031]])

In [28]:
np.random.random_sample(a.shape)

array([[0.2045064 , 0.56540664, 0.10425507, 0.81857494, 0.0954847 ,
        0.84882294, 0.96831253],
       [0.76101188, 0.75425452, 0.60986722, 0.095962  , 0.03127892,
        0.25109555, 0.19968203]])

In [29]:
# Randpom integer valus
np.random.randint(4,7,size=(3,3))

array([[4, 6, 4],
       [4, 4, 6],
       [4, 4, 4]])

In [30]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Repeat an array
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
output=np.ones((5,5))
print(output)

Z= np.zeros((3,3))
Z[1,1]=9
print(Z)

output[1:4,1:4]=Z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be carefull when you coping arrays!!!

In [33]:
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)

[1 2 3]


# Mathematics

In [34]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [35]:
a+2

array([3, 4, 5, 6])

In [36]:
a+2

array([3, 4, 5, 6])

In [37]:
a-2

array([-1,  0,  1,  2])

In [38]:
a*2

array([2, 4, 6, 8])

In [39]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [41]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [42]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [44]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [45]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [47]:
np.vdot(a,b)

12.0

In [48]:
np.outer(a,b)

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [49]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [50]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [51]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

1

In [53]:
np.max(stats, axis=1)

array([3, 6])

In [54]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [55]:
np.mean(stats)

3.5

In [56]:
np.var(stats)

2.9166666666666665

In [57]:
np.cov(stats)

array([[1., 1.],
       [1., 1.]])

In [58]:
np.std(stats)

1.707825127659933

In [59]:
np.sqrt(stats)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Reorganizing Arrays

In [60]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,-1))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [61]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
# Horizontal  stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Array Creation

In [63]:
b=np.empty([2,3])
print(b)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [64]:
np.empty_like(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [65]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [66]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [67]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [68]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [72]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [73]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [74]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [75]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [76]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [77]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [78]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [79]:
np.ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])