# ndarray
ndarraya are time and space_efficint multidimensional arrays at the core of numpy. like the data structure in week 2, lets get started by creating ndarrays using the numpy packages.

In [1]:
import numpy as np
an_array=np.array([3,33,333])

In [2]:
an_array

array([  3,  33, 333])

In [3]:
an_array.shape

(3,)

In [4]:
an_array[0]=555

In [5]:
an_array

array([555,  33, 333])

# How to create Rank 2 numpy array:
A rank 2 ndarray is one with two dimension. Notice the formet below of [[row],[row]]. 2 dimentional array are great for representing matrices whice are often useful in data science.

In [6]:
another=np.array([[11,12,13,14],[21,22,23,24]]) #create a rank 2 array

In [7]:
another

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

# There are many way to create numpy array
Here we create a number of different size arrays with different shapes not different pre-filled value numpy has a number of builds in methods whice help us quickly and easily create multidimensional array.

In [8]:
ex1=np.zeros((2,2))

In [9]:
ex1

array([[0., 0.],
       [0., 0.]])

In [10]:
ex2=np.full((2,2), 9.0)

In [11]:
ex2

array([[9., 9.],
       [9., 9.]])

In [12]:
ex3=np.eye(2,2)

In [13]:
ex3

array([[1., 0.],
       [0., 1.]])

In [14]:
ex4=np.ones((1,2))

In [15]:
ex4

array([[1., 1.]])

In [16]:
ex4.shape

(1, 2)

In [17]:
ex5=np.random.random((2,2))

In [18]:
ex5

array([[0.95801103, 0.59135017],
       [0.3919263 , 0.6067648 ]])

# Array Indexing
Slice indexing - 
Similar to the use of slice indexing with list and strings. We can use the slice indexing to pull out sub-regions of narrays.

In [19]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

In [20]:
an_array

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [21]:
a_slice=an_array[:2, 1:3]

In [22]:
a_slice

array([[12, 13],
       [22, 23]])

# Boolean indexing
Array indexing for changing element:

In [23]:
an_array=np.array([[11,12],[21,22],[31,32]])

In [24]:
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [25]:
filter=(an_array>15)

In [26]:
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [27]:
an_array[(an_array>20)&(an_array<30)]

array([21, 22])

In [28]:
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

# Datatypes and Array Operations
#Datatypes

In [29]:
import numpy as np
ex1=np.array([11, 12])

In [30]:
ex1

array([11, 12])

In [31]:
ex1.dtype

dtype('int32')

In [32]:
ex2=np.array([11.0, 12.0])

In [33]:
ex2

array([11., 12.])

In [34]:
ex2.dtype

dtype('float64')

In [35]:
ex3=np.array([11, 12], dtype=np.int64)

In [36]:
ex3.dtype

dtype('int64')

In [37]:
ex4=np.array([11.7, 12.1], dtype=np.int64)

In [38]:
ex4.dtype

dtype('int64')

# Arithmetic Array Operations

In [39]:
x=np.array([[111,112],[121,122]], dtype=np.int64)
y=np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)
print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [40]:
print(x+y)
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]


In [41]:
print(x-y)
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]


In [42]:
print(x*y)
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]
[[23432.1 23755.2]
 [26753.1 27096.2]]


In [43]:
print(x/y)
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [44]:
# square root
print(np.sqrt(x,y))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [45]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Statistical Methods, Sorting and Set Operatiopns:

# Basic Statistical operations:

In [46]:
# setup a random 2*4 matrix
arr= 10*np.random.randn(2,5)
print(arr)

[[  3.70957319  -5.38141018  12.96590578   5.91664424   5.43712294]
 [-14.94715115   6.78255177   2.23850832   1.60678661  -4.16682826]]


In [47]:
print(arr.mean())

1.4161703255368419


In [48]:
print(arr.mean(axis=-1))

[ 4.52956719 -1.69722654]


In [49]:
# compute the means by colume
print(arr.mean(axis=0))

[-5.61878898  0.70057079  7.60220705  3.76171542  0.63514734]


In [50]:
#sum all the element
print(arr.sum())

14.161703255368419


In [51]:
#compute the medians
print(np.median(arr, axis=1))

[5.43712294 1.60678661]


# Sorting

In [52]:
# createw a 10 element array of randoms
unsorted=np.random.randn(10)
print(unsorted)

[ 1.41401211 -1.80162392 -1.10971368 -1.21490434  1.15913535  0.42629433
 -0.49689983  0.84245308  0.28025225 -2.59159668]


In [53]:
# create copy and sort


# Finding unique element

In [54]:
array=np.array([1,2,1,4,2,1,4,2])
print(array)
print(np.unique(array))

[1 2 1 4 2 1 4 2]
[1 2 4]


# Set Operatiopns with np.array data type:

In [55]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [56]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [57]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [58]:
print(np.setdiff1d(s1,s2)) # element in s1 that are not in s2

['desk']


In [59]:
print(np.in1d(s1,s2)) # which element of s1 is aslo s2

[False  True  True]


# Broadcasting 
Introduction to broadcasting

In [60]:
import numpy as np
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [61]:
# create a rank 1 ndarray with 3 values
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [62]:
y=start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [63]:
# create an ndarray which is 4*1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [64]:
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [65]:
add_scalar=np.array(1)
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1
print(a+b1)
print(a+b2)

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


# Speedtest: ndarrays vs lists


In [67]:
from numpy import arange
from timeit import Timer
size = 1000000
timeits = 1000

In [68]:
nd_array=arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>
